name: Build

on:
  pull_request:
  push:
    branches:
      - dev
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/tinygo-org/tinygo-dev:latest
    steps:
      - name: Free Disk space
        shell: bash
        run: |
          df -h
          rm -rf /opt/hostedtoolcache
          rm -rf /usr/local/lib/android
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/graalvm
          rm -rf /usr/local/share/boost
          df -h
      - name: Work around CVE-2022-24765
        # We're not on a multi-user machine, so this is safe.
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v4
      - name: TinyGo version check
        run: tinygo version
      - name: Enforce Go Formatted Code
        run: make fmt-check
      - name: Run unit tests
        run: make unit-test
      - name: Run build and smoke tests
        run: make smoke-test
